### ISSUE TITLE
IS ITMO

### ISSUE THREAD

**Issue by fish-from-SanDiego** [Verteplushka/IS-Coursework#1]
Даже тут ИС ИТМО, то есть даже студенты ВТ признают его превосходство

**Comment by Verteplushka** [comment]
![ural-my-honest-reaction](https://github.com/user-attachments/assets/62d7deb4-1df5-4fbe-b61b-2b994e07133f)

**Comment by Karabas890** [comment]
![йоу](https://github.com/user-attachments/assets/671f7d15-7030-4440-9f4a-7038ba4021e8)
